### ISSUE TITLE
Failure at startup

### ISSUE THREAD

**Issue by RamSet** [janw/pi-hole-influx#21]
Getting a fat python error at start:
```
[pi@MezelPi:pi-hole-influx]$/usr/bin/python3 /home/pi/pi-hole-influx/piholeinflux.py
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/home/pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 728, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/pi-hole-influx/piholeinflux.py", line 17, in <module>
    settings.validators.register(Validator("INSTANCES", must_exist=True))
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 92, in __getattr__
    self._setup()
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 123, in _setup
    settings_module=settings_module, **self._kwargs
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 186, in __init__
    self.execute_loaders()
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 747, in execute_loaders
    self, env=env, silent=silent, key=key, filename=filename
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/loaders/__init__.py", line 114, in settings_loader
    obj, filename=mod_file, env=env, silent=silent, key=key
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/loaders/toml_loader.py", line 38, in load
    loader.load(filename=filename, key=key, silent=silent)
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/loaders/base.py", line 84, in load
    self._read(files, env_list, silent, key)
  File "/home/pi/.local/lib/python3.5/site-packages/dynaconf/loaders/base.py", line 96, in _read
    source_data = self.file_reader(open_file)
  File "/home/pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/home/pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 11 column 1 char 188)
```

**Comment by RamSet** [comment]
Disregard. User error :)
