### ISSUE TITLE
Job for piholeinflux.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by danktankk** [janw/pi-hole-influx#26]
This is what I see:

```
pi@QTPi:~ $ sudo systemctl start piholeinflux.service
Job for piholeinflux.service failed because the control process exited with error code.
See "systemctl status piholeinflux.service" and "journalctl -xe" for details.

status:
pi@QTPi:~ $ systemctl status piholeinflux.service
● piholeinflux.service - Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization
   Loaded: loaded (/home/pi/pi-hole-influx/piholeinflux.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-08-04 15:33:37 EDT; 7s ago
     Docs: https://github.com/janw/pi-hole-influx
  Process: 3510 ExecStart=/usr/bin/python3 /home/pi/pi-hole-influx/piholeinflux.py (code=exited, status=1/FAILURE)
 Main PID: 3510 (code=exited, status=1/FAILURE)

Aug 04 15:33:37 QTPi systemd[1]: piholeinflux.service: Unit entered failed state.
Aug 04 15:33:37 QTPi systemd[1]: piholeinflux.service: Failed with result 'exit-code'.


journalctl output:
pi@QTPi:~ $ sudo journalctl -xe
-- Unit piholeinflux.service has finished shutting down.
Aug 04 15:40:33 QTPi systemd[1]: Starting Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization...
-- Subject: Unit piholeinflux.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit piholeinflux.service has begun starting up.
Aug 04 15:40:35 QTPi python3[3776]: INFO: [pihole.localhost] Initialized for localhost (http://127.0.0.1/admin/api.php)
Aug 04 15:40:35 QTPi python3[3776]: INFO: [__main__] Running daemon, reporting to InfluxDB at 127.0.0.1.
Aug 04 15:40:35 QTPi python3[3776]: ERROR: [pihole.localhost] Got unexpected response 404, b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html
Aug 04 15:40:35 QTPi python3[3776]: ERROR: [__main__] Unexpected exception
Aug 04 15:40:35 QTPi python3[3776]: Traceback (most recent call last):
Aug 04 15:40:35 QTPi python3[3776]:   File "/home/pi/pi-hole-influx/piholeinflux.py", line 112, in main
Aug 04 15:40:35 QTPi python3[3776]:     daemon.run()
Aug 04 15:40:35 QTPi python3[3776]:   File "/home/pi/pi-hole-influx/piholeinflux.py", line 80, in run
Aug 04 15:40:35 QTPi python3[3776]:     self.send_msg(data, pi.name)
Aug 04 15:40:35 QTPi python3[3776]:   File "/home/pi/pi-hole-influx/piholeinflux.py", line 91, in send_msg
Aug 04 15:40:35 QTPi python3[3776]:     if "gravity_last_updated" in resp:
Aug 04 15:40:35 QTPi python3[3776]: TypeError: argument of type 'NoneType' is not iterable
Aug 04 15:40:35 QTPi systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Aug 04 15:40:35 QTPi systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has failed
```

I followed the install to the letter afaik, however I get this error when I try to run the service.  Any ideas on how to correct would be great!  Thanks for any help.

**Comment by janw** [comment]
> Got unexpected response 404, b'\n<html

makes me think the pi-hole API URL you have given the daemon is not correct. Have you checked it works in your browser?

**Comment by danktankk** [comment]
Hey, thanks for responding.

it looks like i get a 404 there as well...

http://192.168.20.140/admin/api.php
or 
http://127.0.0.1/admin/api.php

The requested URL /admin/api.php was not found on this server.
Apache/2.4.25 (Raspbian) Server at 192.168.20.140 Port 80

Im not sure why i would be getting that either.  Any ideas?

Thanks again.

**Comment by danktankk** [comment]
Another thought, shouldn't i get a 404 _because_ the service failed to start?  Wouldnt that be more of a consequence of that rather than the problem?  Thanks again.

**Comment by danktankk** [comment]
ok so I just did an install for raspberry pi & skipped your instructions completely and now your service starts with no issue.

Fixed it with this one command:

curl -sSL https://install.pi-hole.net | bash

**Comment by janw** [comment]
It sure does help to actually install Pi-hole itself. Glad you could make it work.
