### ISSUE TITLE
python3.5 error on startup

### ISSUE THREAD

**Issue by RedOrion** [janw/pi-hole-influx#34]
Receiving this error below upon launching `piholeinflux.py`. As far as I can tell this should support python3.5. Am I missing something?

```
Pi@PiHole:~/pi-hole-influx$ ./piholeinflux.py 
Traceback (most recent call last):
  File "/home/Pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/home/Pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/Pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 832, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./piholeinflux.py", line 17, in <module>
    settings.validators.register(Validator("INSTANCES", must_exist=True))
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 95, in __getattr__
    self._setup()
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 126, in _setup
    settings_module=settings_module, **self._kwargs
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 190, in __init__
    self.execute_loaders()
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/base.py", line 850, in execute_loaders
    self, env=env, silent=silent, key=key, filename=filename
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/loaders/__init__.py", line 116, in settings_loader
    obj, filename=mod_file, env=env, silent=silent, key=key
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/loaders/toml_loader.py", line 38, in load
    loader.load(filename=filename, key=key, silent=silent)
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/loaders/base.py", line 71, in load
    self._read(files, env_list, silent, key)
  File "/home/Pi/.local/lib/python3.5/site-packages/dynaconf/loaders/base.py", line 83, in _read
    source_data = self.file_reader(open_file)
  File "/home/Pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/home/Pi/.local/lib/python3.5/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 3 column 1 char 10)
```

**Comment by janw** [comment]
Could you post your TOML config file?

**Comment by RedOrion** [comment]
[global]

influxdb_host = influxdb.local
influxdb_port = 8086
influxdb_database = pihole
influxdb_username = pihole
influxdb_password = pihole
# influxdb_ssl = "False"

# request_timeout = 10
# reporting_interval = 30

instances="localhost=http://127.0.0.1/admin/api.php"
# instances={pihole="http://10.10.0.10/admin/api.php", second instance="http://1
92.168.0.1/admin/api.php"}
# instances=["http://10.10.0.10/admin/api.php", "http://192.168.0.1/admin/api.ph
p"]

**Comment by janw** [comment]
The issue might be that strings in the TOML file have to always be wrapped in `"…"`. So 

```toml
[global]

influxdb_host = "influxdb.local"
influxdb_port = 8086
influxdb_database = "pihole"
influxdb_username = "pihole"
influxdb_password = "pihole"
instances="localhost=http://127.0.0.1/admin/api.php"
```

That is not obvious from the documentation or example file, sorry about that.

**Comment by RedOrion** [comment]
No worries. Closing.

**Comment by RedOrion** [comment]
Pull request submitted with comments
