### ISSUE TITLE
pi-hole-influx on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by wharris623** [janw/pi-hole-influx#36]
Hi there!  This is an awesome project and I'm trying to get it working on  Ubuntu 18.04.2 LTS.  Have you or anyone had any luck with this?  What I'm running into right now is the following error according to journalctl -xe

Any ideas?

Thanks in advance!

Wes

Oct 13 02:02:39 blackhole systemd[1]: Starting Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization...
-- Subject: Unit piholeinflux.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit piholeinflux.service has begun starting up.
Oct 13 02:02:39 blackhole python3[49784]: Traceback (most recent call last):
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/toml/decoder.py", line 456, in loads
Oct 13 02:02:39 blackhole python3[49784]:     multibackslash)
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/toml/decoder.py", line 678, in load_line
Oct 13 02:02:39 blackhole python3[49784]:     raise ValueError("Invalid date or number")
Oct 13 02:02:39 blackhole python3[49784]: ValueError: Invalid date or number
Oct 13 02:02:39 blackhole python3[49784]: During handling of the above exception, another exception occurred:
Oct 13 02:02:39 blackhole python3[49784]: Traceback (most recent call last):
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/pi-hole-influx/piholeinflux.py", line 17, in <module>
Oct 13 02:02:39 blackhole python3[49784]:     settings.validators.register(Validator("INSTANCES", must_exist=True))
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/base.py", line 96, in __getattr__
Oct 13 02:02:39 blackhole python3[49784]:     self._setup()
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/base.py", line 127, in _setup
Oct 13 02:02:39 blackhole python3[49784]:     settings_module=settings_module, **self._kwargs
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/base.py", line 191, in __init__
Oct 13 02:02:39 blackhole python3[49784]:     self.execute_loaders()
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/base.py", line 883, in execute_loaders
Oct 13 02:02:39 blackhole python3[49784]:     self, env=env, silent=silent, key=key, filename=filename
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/loaders/__init__.py", line 126, in settings_loader
Oct 13 02:02:39 blackhole python3[49784]:     obj, filename=mod_file, env=env, silent=silent, key=key
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/loaders/toml_loader.py", line 38, in load
Oct 13 02:02:39 blackhole python3[49784]:     loader.load(filename=filename, key=key, silent=silent)
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/loaders/base.py", line 72, in load
Oct 13 02:02:39 blackhole python3[49784]:     self._read(files, env_list, silent, key)
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/dynaconf/loaders/base.py", line 84, in _read
Oct 13 02:02:39 blackhole python3[49784]:     source_data = self.file_reader(open_file)
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/toml/decoder.py", line 134, in load
Oct 13 02:02:39 blackhole python3[49784]:     return loads(f.read(), _dict, decoder)
Oct 13 02:02:39 blackhole python3[49784]:   File "/home/wes/.local/lib/python3.6/site-packages/toml/decoder.py", line 458, in loads
Oct 13 02:02:39 blackhole python3[49784]:     raise TomlDecodeError(str(err), original, pos)
Oct 13 02:02:39 blackhole python3[49784]: toml.decoder.TomlDecodeError: Invalid date or number (line 3 column 1 char 10)
Oct 13 02:02:39 blackhole systemd[1]: piholeinflux.service: Main process exited, code=exited, status=1/FAILURE
Oct 13 02:02:39 blackhole systemd[1]: piholeinflux.service: Failed with result 'exit-code'.
Oct 13 02:02:39 blackhole systemd[1]: Failed to start Pi-hole-Influx - Send Pi-hole statistics to InfluxDB for visualization.
-- Subject: Unit piholeinflux.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit piholeinflux.service has failed.
--

**Comment by wharris623** [comment]
I got it.  In the user.toml the entries have to be in quotes.  It's not like that in the example file.  

user.toml.example shows
```
[global]

# influxdb_host =
# influxdb_port =
# influxdb_database =
# influxdb_username =
# influxdb_password =

# request_timeout = 10
# reporting_interval = 30

# instances="localhost=http://127.0.0.1/admin/api.php"
# instances={pihole="http://10.10.0.10/admin/api.php", second instance="http://192.168.0.1/admin/api.php"}
# instances=["http://10.10.0.10/admin/api.php", "http://192.168.0.1/admin/api.php"]

```

when it should be
```
[global]

# influxdb_host = ""
# influxdb_port = ""
# influxdb_database = ""
# influxdb_username = ""
# influxdb_password = ""

# request_timeout = "10"
# reporting_interval = "30"

# instances="localhost=http://127.0.0.1/admin/api.php"
# instances={pihole="http://10.10.0.10/admin/api.php", second instance="http://192.168.0.1/admin/api.php"}
# instances=["http://10.10.0.10/admin/api.php", "http://192.168.0.1/admin/api.php"]
```
