### ISSUE TITLE
Docker crashes on Synology

### ISSUE THREAD

**Issue by AlfaJackal** [janw/pi-hole-influx#40]
Any ideas why? I would really appreciate a hint or solution!

```
Traceback (most recent call last):
  File "./piholeinflux.py", line 18, in <module>
    settings.validators.validate()
  File "/usr/local/lib/python3.8/site-packages/dynaconf/validator.py", line 215, in validate
    validator.validate(self.settings)
  File "/usr/local/lib/python3.8/site-packages/dynaconf/validator.py", line 147, in validate
    self._validate_items(settings, settings.current_env)
  File "/usr/local/lib/python3.8/site-packages/dynaconf/validator.py", line 160, in _validate_items
    raise ValidationError(
dynaconf.validator.ValidationError: INSTANCES is required in env DEVELOPMENT
Traceback (most recent call last):
  File "./piholeinflux.py", line 18, in <module>
    settings.validators.validate()
  File "/usr/local/lib/python3.8/site-packages/dynaconf/validator.py", line 215, in validate
    validator.validate(self.settings)
  File "/usr/local/lib/python3.8/site-packages/dynaconf/validator.py", line 147, in validate
    self._validate_items(settings, settings.current_env)
  File "/usr/local/lib/python3.8/site-packages/dynaconf/validator.py", line 160, in _validate_items
    raise ValidationError(
dynaconf.validator.ValidationError: INSTANCES is required in env DEVELOPMENT
```

My config.ini
```
    [influxdb]
    port = 32784
    hostname = 10.10.0.6
    username = pihole
    password = pihole
    database = pihole
	
    # Time between reports to InfluxDB (in seconds)
    reporting_interval = 10
	
    [pihole]
    api_location = http://10.0.0.13/admin/api.php
    instance_name = pihole
    timeout = 10
```

My Dockerfile:
```
    FROM alpine as builder
    RUN apk add --no-cache git
    WORKDIR /app
    RUN git clone https://github.com/janw/pi-hole-influx.git
    FROM python:3-alpine
    WORKDIR /usr/src/app
    COPY --from=builder /app/pi-hole-influx/requirements.txt /usr/src/app
    RUN pip install --no-cache-dir -r requirements.txt
    COPY --from=builder /app/pi-hole-influx/piholeinflux.py /usr/src/app
    COPY config.ini .
    CMD [ "python", "./piholeinflux.py" ]
```

**Comment by AlfaJackal** [comment]
I am using another PiHole script now. Got support there, everything is working very well.
