### ISSUE TITLE
SSL validation error when pihole admin interface is HTTPS

### ISSUE THREAD

**Issue by nomad64** [janw/pi-hole-influx#43]
When pihole's admin interface is running on HTTPS (https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771), requests tries to verify the SSL cert. Since my cert is signed by my internal CA, requests thinks it is invalid and does not connect. After several tries, the container crashes.

Exception output below.

    INFO: [pihole.pihpvha] Initialized for pihpvha (http://PIHOLE_FQDN/admin/api.php)
    INFO: [__main__] Running daemon, reporting to InfluxDB at INFLUXDB_FQDN.
    ERROR: [__main__] Unexpected exception
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
        chunked=chunked,
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
        self._validate_conn(conn)
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
        conn.connect()
      File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
        ssl_context=context,
      File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
        _context=self, _session=session)
      File "/usr/local/lib/python3.6/ssl.py", line 817, in __init__
        self.do_handshake()
      File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
        self._sslobj.do_handshake()
      File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='PIHOLE_FQDN', port=443): Max retries exceeded with url: /admin/api.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "./piholeinflux.py", line 114, in main
        daemon.run()
      File "./piholeinflux.py", line 81, in run
    requests.exceptions.SSLError: HTTPSConnectionPool(host='PIHOLE_FQDN', port=443): Max retries exceeded with url: /admin/api.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

**Comment by janw** [comment]
Hi @nomad64. I added the ability to disable SSL verification in 9e45970 just now. Add 
```toml
request_verify_ssl = false
```
to your user.toml config for it to work.

**Comment by nomad64** [comment]
Sorry for the delay in getting back to this - been a busy few days.

I re-deployed the latest version of the docker image with a custom user.toml file, and the stats are reporting properly.

Thanks!
